---
title: "Resume"
format:
  html:
    toc: true
    toc-location: right
    html-math-method: katex
title-block-banner: true
---

## BACKGROUND

I have been fortunate enough to have the opportunity to explore a wide range of industries that have captured my interest. My work experience began with a three-year stint at a fast-food restaurant, where I learned the value of loyalty and dedication. In between those three years, I worked as a tutor at a local middle school, hoping to explore a career in education and later as an intern at the Oregon Environmental Council to pursue my interest in environmental justice.

Following my internship, I worked as an oral health educator assistant at the Boys & Girls Club, Health and Dental Services Center. I loved being in scrubs every day and felt like I was making a personal difference in the lives of the students we served. This experience led me to pursue a career in oral healthcare, where I provided chairside dental care as a dental assistant. However, during the pandemic, I began feeling burnt out and decided to return to community college to fulfill necessary prerequisites for dental school.

While I was unsure of my next step, I made the difficult decision to leave my dental assisting job after thoughtful consideration. I then spent three months in Mexico connecting with my roots. It was during this time that I received an email informing me that I had been awarded a scholarship that would cover my tuition and allow me to transfer to Western Oregon University. It was here that I fell in love with my public health education classes, and shortly after my first term, I declared myself a public health major.

Throughout my professional journey, I have honed my skills in communication, easily adapting to new environments, and taking on leadership roles with enthusiasm. Public speaking has been a consistent part of many of my positions, and I enjoy sharing my knowledge and experiences with others. I am excited to continue growing and learning in my future endeavors.

## GOAL

While I have not yet decided on a specific career path, my academic journey in public health has been incredibly fulfilling thus far. I am passionate about this field as it combines all of my interests and allows me to showcase some of my best qualities in my coursework.

However, I am also aware of the importance of gaining practical experience in the public health field. As such, I am actively seeking out internship opportunities that will enable me to apply the knowledge and skills I have gained through my coursework to real-world situations.

In addition to my coursework and internship pursuits, I am currently preparing for the Certified Health Education Specialist (CHES) examination. Passing this exam will demonstrate my competency in the Eight Areas of Responsibility for Health Education Specialists.

I am eager to continue expanding my knowledge and discovering my true passion within the field. Ultimately, my goal is to make a meaningful contribution to the industry and make a positive impact on the lives of individuals and communities.

## EDUCATION

Western Oregon University, Monmouth, Oregon \| B.S. in Public Health \| Expected June 2024

Chemeketa Community College, Salem,, OR \| A.G.S. \| September 2016 - June 2022

## PROFESSIONAL EXPERIENCE

Student Worker \| Western Oregon University Salem Extension Office \| October 2022 - Present

-   Onsite support for digital equipment assistance

Orthodontic Dental Assistant \| Castilla Orthodontics \| October 2020 - Aug 2022

-   Independent chair side dental care

-   Communicated effectively with general public from diverse backgrounds

Oral Health Educator Assistant \| Boys & Girls Clubs of Salem \| July 2019 - October 2020

-   Lead outreach and connection efforts to students and families in need of dental assistance

## LANGUAGES

I am a native English speaker and I am also proficient in Spanish with the ability to communicate effectively and respectfully with Spanish-speaking individuals. I was a freelance medical interpreter with Professional Interpreters Inc. from November 2021 through February 2023.
